# New Download (2mTemp, Dewpoint, Cloud Cover, CAPE & CIN)

In [1]:
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

In [11]:
#Date range for FastHerbie
DATES = pd.date_range(
    start="2026-04-15 00:00",
    periods=41,
    freq="1h",
)

# Create a range of forecast lead times
fxx = list(range(0, 24))

DATES, fxx

(DatetimeIndex(['2026-04-15 00:00:00', '2026-04-15 01:00:00',
                '2026-04-15 02:00:00', '2026-04-15 03:00:00',
                '2026-04-15 04:00:00', '2026-04-15 05:00:00',
                '2026-04-15 06:00:00', '2026-04-15 07:00:00',
                '2026-04-15 08:00:00', '2026-04-15 09:00:00',
                '2026-04-15 10:00:00', '2026-04-15 11:00:00',
                '2026-04-15 12:00:00', '2026-04-15 13:00:00',
                '2026-04-15 14:00:00', '2026-04-15 15:00:00',
                '2026-04-15 16:00:00', '2026-04-15 17:00:00',
                '2026-04-15 18:00:00', '2026-04-15 19:00:00',
                '2026-04-15 20:00:00', '2026-04-15 21:00:00',
                '2026-04-15 22:00:00', '2026-04-15 23:00:00',
                '2026-04-16 00:00:00', '2026-04-16 01:00:00',
                '2026-04-16 02:00:00', '2026-04-16 03:00:00',
                '2026-04-16 04:00:00', '2026-04-16 05:00:00',
                '2026-04-16 06:00:00', '2026-04-16 07:00:00',
                '2026-04-16 08:00:00', '2026-04-16 09:00:00',
                '2026-04-16 10:00:00', '2026-04-16 11:00:00',
                '2026-04-16 12:00:00', '2026-04-16 13:00:00',
                '2026-04-16 14:00:00', '2026-04-16 15:00:00',
                '2026-04-16 16:00:00'],
               dtype='datetime64[ns]', freq='h'),
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23])

In [12]:
FH = FastHerbie(DATES, model="hrrr", fxx=fxx)
FH

Could not find 128/856 GRIB files.

In [13]:
FH.objects, len(FH.objects)

([▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 00:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 01:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 02:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 03:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 04:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 05:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F19 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F20 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F21 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F22 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 06:00 UTC F23 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 07:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F15 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F16 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F17 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F18 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F19 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F20 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F21 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F22 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 08:00 UTC F23 ┊ source=None,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F00 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F01 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F02 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F03 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F04 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F05 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F06 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F07 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F08 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F09 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F10 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F11 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F12 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F13 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F14 ┊ source=aws,
  ▌▌Herbie HRRR model sfc product initialized 2026-Apr-15 09:00 UTC F15 ┊ source=aws,

In [14]:
run = "2026-04-15 00:00" #must be 00:00 to not drop files.

In [15]:
H = FastHerbie([run], model="hrrr", fxx=np.arange(0,49,1).tolist(), save_dir='meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads', overwrite=True)

In [16]:
H.inventory(':DPT:2 m above')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,74,41245489,42471688.0,41245489-42471688,2026-04-15,2026-04-15 00:00:00,DPT,2 m above ground,anl,:DPT:2 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,74,47031931,48197165.0,47031931-48197165,2026-04-15,2026-04-15 01:00:00,DPT,2 m above ground,1 hour fcst,:DPT:2 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,74,47565579,48713611.0,47565579-48713611,2026-04-15,2026-04-15 02:00:00,DPT,2 m above ground,2 hour fcst,:DPT:2 m above ground:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,74,48267211,49436639.0,48267211-49436639,2026-04-15,2026-04-15 03:00:00,DPT,2 m above ground,3 hour fcst,:DPT:2 m above ground:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,74,48442701,49608183.0,48442701-49608183,2026-04-15,2026-04-15 04:00:00,DPT,2 m above ground,4 hour fcst,:DPT:2 m above ground:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,74,49095164,50288307.0,49095164-50288307,2026-04-15,2026-04-15 05:00:00,DPT,2 m above ground,5 hour fcst,:DPT:2 m above ground:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,74,49652203,50854600.0,49652203-50854600,2026-04-15,2026-04-15 06:00:00,DPT,2 m above ground,6 hour fcst,:DPT:2 m above ground:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,74,51081100,52294526.0,51081100-52294526,2026-04-15,2026-04-15 07:00:00,DPT,2 m above ground,7 hour fcst,:DPT:2 m above ground:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,74,51270754,52492182.0,51270754-52492182,2026-04-15,2026-04-15 08:00:00,DPT,2 m above ground,8 hour fcst,:DPT:2 m above ground:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,74,52258913,53486320.0,52258913-53486320,2026-04-15,2026-04-15 09:00:00,DPT,2 m above ground,9 hour fcst,:DPT:2 m above ground:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,74,52554157,53785162.0,52554157-53785162,2026-04-15,2026-04-15 10:00:00,DPT,2 m above ground,10 hour fcst,:DPT:2 m above ground:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,74,52674516,53923383.0,52674516-53923383,2026-04-15,2026-04-15 11:00:00,DPT,2 m above ground,11 hour fcst,:DPT:2 m above ground:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,74,52735334,53981961.0,52735334-53981961,2026-04-15,2026-04-15 12:00:00,DPT,2 m above ground,12 hour fcst,:DPT:2 m above ground:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,74,52657718,53883040.0,52657718-53883040,2026-04-15,2026-04-15 13:00:00,DPT,2 m above ground,13 hour fcst,:DPT:2 m above ground:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,74,52812415,54052011.0,52812415-54052011,2026-04-15,2026-04-15 14:00:00,DPT,2 m above ground,14 hour fcst,:DPT:2 m above ground:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,74,52702655,53948508.0,52702655-53948508,2026-04-15,2026-04-15 15:00:00,DPT,2 m above ground,15 hour fcst,:DPT:2 m above ground:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,74,51763383,53000683.0,51763383-53000683,2026-04-15,2026-04-15 16:00:00,DPT,2 m above ground,16 hour fcst,:DPT:2 m above ground:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,74,51290994,52521509.0,51290994-52521509,2026-04-15,2026-04-15 17:00:00,DPT,2 m above ground,17 hour fcst,:DPT:2 m above ground:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,74,51214945,52442214.0,51214945-52442214,2026-04-15,2026-04-15 18:00:00,DPT,2 m above ground,18 hour fcst,:DPT:2 m above ground:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,74,51246847,52472851.0,51246847-52472851,2026-04-15,2026-04-15 19:00:00,DPT,2 m above ground,19 hour fcst,:DPT:2 m above ground:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,74,50515224,51740740.0,50515224-51740740,2026-04-15,2026-04-15 20:00:00,DPT,2 m above ground,20 hour fcst,:DPT:2 m above ground:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,74,50584672,51811015.0,50584672-51811015,2026-04-15,2026-04-15 21:00:00,DPT,2 m above ground,21 hour fcst,:DPT:2 m above ground:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,74,50999264,52224610.0,50999264-52224610,2026-04-15,2026-04-15 22:00:00,DPT,2 m above ground,22 hour fcst,:DPT:2 m above ground:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,74,51209962,52435297.0,51209962-52435297,2026-04-15,2026-04-15 23:00:00,DPT,2 m above ground,23 hour fcst,:DPT:2 m above ground:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,74,51222879,52443680.0,51222879-52443680,2026-04-15,2026-04-16 00:00:00,DPT,2 m above ground,24 hour fcst,:DPT:2 m above ground:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,74,51348618,52554845.0,51348618-52554845,2026-04-15,2026-04-16 01:00:00,DPT,2 m above ground,25 hour fcst,:DPT:2 m above ground:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,74,51079970,52274300.0,51079970-52274300,2026-04-15,2026-04-16 02:00:00,DPT,2 m above ground,26 hour fcst,:DPT:2 m above ground:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,74,51574930,52770322.0,51574930-52770322,2026-04-15,2026-04-16 03:00:00,DPT,2 m above ground,27 hour fcst,:DPT:2 m above ground:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,74,52929350,54129676.0,52929350-54129676,2026-04-15,2026-04-16 04:00:00,DPT,2 m above ground,28 hour fcst,:DPT:2 m above ground:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,74,53233174,54436983.0,53233174-54436983,2026-04-15,2026-04-16 05:00:00,DPT,2 m above ground,29 hour fcst,:DPT:2 m above ground:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,74,53018982,54240078.0,53018982-54240078,2026-04-15,2026-04-16 06:00:00,DPT,2 m above ground,30 hour fcst,:DPT:2 m above ground:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,74,53382602,54604645.0,53382602-54604645,2026-04-15,2026-04-16 07:00:00,DPT,2 m above ground,31 hour fcst,:DPT:2 m above ground:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,74,53989294,55215820.0,53989294-55215820,2026-04-15,2026-04-16 08:00:00,DPT,2 m above ground,32 hour fcst,:DPT:2 m above ground:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,74,53316795,54546494.0,53316795-54546494,2026-04-15,2026-04-16 09:00:00,DPT,2 m above ground,33 hour fcst,:DPT:2 m above ground:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,74,53504503,54721175.0,53504503-54721175,2026-04-15,2026-04-16 10:00:00,DPT,2 m above ground,34 hour fcst,:DPT:2 m above ground:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,74,53134246,54368978.0,53134246-54368978,2026-04-15,2026-04-16 11:00:00,DPT,2 m above ground,35 hour fcst,:DPT:2 m above ground:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,74,53198960,54418816.0,53198960-54418816,2026-04-15,2026-04-16 12:00:00,DPT,2 m above ground,36 hour fcst,:DPT:2 m above ground:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,74,53751902,54983474.0,53751902-54983474,2026-04-15,2026-04-16 13:00:00,DPT,2 m above ground,37 hour fcst,:DPT:2 m above ground:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,74,53441017,54689878.0,53441017-54689878,2026-04-15,2026-04-16 14:00:00,DPT,2 m above ground,38 hour fcst,:DPT:2 m above ground:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,74,52529868,53768793.0,52529868-53768793,2026-04-15,2026-04-16 15:00:00,DPT,2 m above ground,39 hour fcst,:DPT:2 m above ground:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,74,52024593,53259390.0,52024593-53259390,2026-04-15,2026-04-16 16:00:00,DPT,2 m above ground,40 hour fcst,:DPT:2 m above ground:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,74,52041132,53289098.0,52041132-53289098,2026-04-15,2026-04-16 17:00:00,DPT,2 m above ground,41 hour fcst,:DPT:2 m above ground:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,74,51480801,52729289.0,51480801-52729289,2026-04-15,2026-04-16 18:00:00,DPT,2 m above ground,42 hour fcst,:DPT:2 m above ground:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,74,51262381,52496454.0,51262381-52496454,2026-04-15,2026-04-16 19:00:00,DPT,2 m above ground,43 hour fcst,:DPT:2 m above ground:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,74,51357355,52594159.0,51357355-52594159,2026-04-15,2026-04-16 20:00:00,DPT,2 m above ground,44 hour fcst,:DPT:2 m above ground:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,74,51572977,52811137.0,51572977-52811137,2026-04-15,2026-04-16 21:00:00,DPT,2 m above ground,45 hour fcst,:DPT:2 m above ground:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,74,51728260,52967305.0,51728260-52967305,2026-04-15,2026-04-16 22:00:00,DPT,2 m above ground,46 hour fcst,:DPT:2 m above ground:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,74,51596263,52835132.0,51596263-52835132,2026-04-15,2026-04-16 23:00:00,DPT,2 m above ground,47 hour fcst,:DPT:2 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,74,50621238,51848887.0,50621238-51848887,2026-04-15,2026-04-17 00:00:00,DPT,2 m above ground,48 hour fcst,:DPT:2 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [17]:
H.inventory(':CIN:surface:')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,106,64409416,64768530.0,64409416-64768530,2026-04-15,2026-04-15 00:00:00,CIN,surface,anl,:CIN:surface:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,106,71893419,72666254.0,71893419-72666254,2026-04-15,2026-04-15 01:00:00,CIN,surface,1 hour fcst,:CIN:surface:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,109,73445377,73800629.0,73445377-73800629,2026-04-15,2026-04-15 02:00:00,CIN,surface,2 hour fcst,:CIN:surface:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,109,74667904,75390418.0,74667904-75390418,2026-04-15,2026-04-15 03:00:00,CIN,surface,3 hour fcst,:CIN:surface:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,109,74616245,75307025.0,74616245-75307025,2026-04-15,2026-04-15 04:00:00,CIN,surface,4 hour fcst,:CIN:surface:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,109,75507003,75816818.0,75507003-75816818,2026-04-15,2026-04-15 05:00:00,CIN,surface,5 hour fcst,:CIN:surface:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,109,76463925,77122087.0,76463925-77122087,2026-04-15,2026-04-15 06:00:00,CIN,surface,6 hour fcst,:CIN:surface:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,109,77463790,78104100.0,77463790-78104100,2026-04-15,2026-04-15 07:00:00,CIN,surface,7 hour fcst,:CIN:surface:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,109,78321280,78590990.0,78321280-78590990,2026-04-15,2026-04-15 08:00:00,CIN,surface,8 hour fcst,:CIN:surface:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,109,79256780,79869327.0,79256780-79869327,2026-04-15,2026-04-15 09:00:00,CIN,surface,9 hour fcst,:CIN:surface:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,109,79724724,80329600.0,79724724-80329600,2026-04-15,2026-04-15 10:00:00,CIN,surface,10 hour fcst,:CIN:surface:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,109,80007002,80607831.0,80007002-80607831,2026-04-15,2026-04-15 11:00:00,CIN,surface,11 hour fcst,:CIN:surface:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,109,80406932,81005902.0,80406932-81005902,2026-04-15,2026-04-15 12:00:00,CIN,surface,12 hour fcst,:CIN:surface:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,109,80451042,81052886.0,80451042-81052886,2026-04-15,2026-04-15 13:00:00,CIN,surface,13 hour fcst,:CIN:surface:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,109,80602511,81222409.0,80602511-81222409,2026-04-15,2026-04-15 14:00:00,CIN,surface,14 hour fcst,:CIN:surface:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,109,81086276,81730444.0,81086276-81730444,2026-04-15,2026-04-15 15:00:00,CIN,surface,15 hour fcst,:CIN:surface:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,109,79972069,80642494.0,79972069-80642494,2026-04-15,2026-04-15 16:00:00,CIN,surface,16 hour fcst,:CIN:surface:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,109,79447432,80120799.0,79447432-80120799,2026-04-15,2026-04-15 17:00:00,CIN,surface,17 hour fcst,:CIN:surface:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,109,78890306,79565722.0,78890306-79565722,2026-04-15,2026-04-15 18:00:00,CIN,surface,18 hour fcst,:CIN:surface:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,109,78880190,79563392.0,78880190-79563392,2026-04-15,2026-04-15 19:00:00,CIN,surface,19 hour fcst,:CIN:surface:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,109,78801624,79495938.0,78801624-79495938,2026-04-15,2026-04-15 20:00:00,CIN,surface,20 hour fcst,:CIN:surface:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,109,78138998,78850315.0,78138998-78850315,2026-04-15,2026-04-15 21:00:00,CIN,surface,21 hour fcst,:CIN:surface:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,109,78668329,79407757.0,78668329-79407757,2026-04-15,2026-04-15 22:00:00,CIN,surface,22 hour fcst,:CIN:surface:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,109,78010308,78749243.0,78010308-78749243,2026-04-15,2026-04-15 23:00:00,CIN,surface,23 hour fcst,:CIN:surface:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,109,78960536,79286469.0,78960536-79286469,2026-04-15,2026-04-16 00:00:00,CIN,surface,24 hour fcst,:CIN:surface:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,109,79079064,79794089.0,79079064-79794089,2026-04-15,2026-04-16 01:00:00,CIN,surface,25 hour fcst,:CIN:surface:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,109,78259573,78948713.0,78259573-78948713,2026-04-15,2026-04-16 02:00:00,CIN,surface,26 hour fcst,:CIN:surface:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,109,79159299,79456946.0,79159299-79456946,2026-04-15,2026-04-16 03:00:00,CIN,surface,27 hour fcst,:CIN:surface:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,109,80494405,81141451.0,80494405-81141451,2026-04-15,2026-04-16 04:00:00,CIN,surface,28 hour fcst,:CIN:surface:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,109,80760675,81382552.0,80760675-81382552,2026-04-15,2026-04-16 05:00:00,CIN,surface,29 hour fcst,:CIN:surface:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,109,81066481,81681898.0,81066481-81681898,2026-04-15,2026-04-16 06:00:00,CIN,surface,30 hour fcst,:CIN:surface:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,109,81480126,82088280.0,81480126-82088280,2026-04-15,2026-04-16 07:00:00,CIN,surface,31 hour fcst,:CIN:surface:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,109,82188402,82806479.0,82188402-82806479,2026-04-15,2026-04-16 08:00:00,CIN,surface,32 hour fcst,:CIN:surface:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,109,81343287,81962436.0,81343287-81962436,2026-04-15,2026-04-16 09:00:00,CIN,surface,33 hour fcst,:CIN:surface:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,109,81620134,82233138.0,81620134-82233138,2026-04-15,2026-04-16 10:00:00,CIN,surface,34 hour fcst,:CIN:surface:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,109,81354256,81958057.0,81354256-81958057,2026-04-15,2026-04-16 11:00:00,CIN,surface,35 hour fcst,:CIN:surface:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,109,81715450,82314328.0,81715450-82314328,2026-04-15,2026-04-16 12:00:00,CIN,surface,36 hour fcst,:CIN:surface:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,109,82132124,82746220.0,82132124-82746220,2026-04-15,2026-04-16 13:00:00,CIN,surface,37 hour fcst,:CIN:surface:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,109,82211412,82834921.0,82211412-82834921,2026-04-15,2026-04-16 14:00:00,CIN,surface,38 hour fcst,:CIN:surface:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,109,81295104,81930531.0,81295104-81930531,2026-04-15,2026-04-16 15:00:00,CIN,surface,39 hour fcst,:CIN:surface:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,109,80579964,81210992.0,80579964-81210992,2026-04-15,2026-04-16 16:00:00,CIN,surface,40 hour fcst,:CIN:surface:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,109,79669282,80304021.0,79669282-80304021,2026-04-15,2026-04-16 17:00:00,CIN,surface,41 hour fcst,:CIN:surface:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,109,79724361,80360930.0,79724361-80360930,2026-04-15,2026-04-16 18:00:00,CIN,surface,42 hour fcst,:CIN:surface:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,109,79203181,79845715.0,79203181-79845715,2026-04-15,2026-04-16 19:00:00,CIN,surface,43 hour fcst,:CIN:surface:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,109,79036561,79687850.0,79036561-79687850,2026-04-15,2026-04-16 20:00:00,CIN,surface,44 hour fcst,:CIN:surface:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,109,79155869,79820868.0,79155869-79820868,2026-04-15,2026-04-16 21:00:00,CIN,surface,45 hour fcst,:CIN:surface:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,109,79146472,79821603.0,79146472-79821603,2026-04-15,2026-04-16 22:00:00,CIN,surface,46 hour fcst,:CIN:surface:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,109,79491124,80183810.0,79491124-80183810,2026-04-15,2026-04-16 23:00:00,CIN,surface,47 hour fcst,:CIN:surface:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,109,78286762,78999609.0,78286762-78999609,2026-04-15,2026-04-17 00:00:00,CIN,surface,48 hour fcst,:CIN:surface:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [18]:
H.inventory(':UGRD:10 m above')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,77,44464468,46846082.0,44464468-46846082,2026-04-15,2026-04-15 00:00:00,UGRD,10 m above ground,anl,:UGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,77,50392895,52774509.0,50392895-52774509,2026-04-15,2026-04-15 01:00:00,UGRD,10 m above ground,1 hour fcst,:UGRD:10 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,77,50925514,53307128.0,50925514-53307128,2026-04-15,2026-04-15 02:00:00,UGRD,10 m above ground,2 hour fcst,:UGRD:10 m above ground:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,77,51790808,54172422.0,51790808-54172422,2026-04-15,2026-04-15 03:00:00,UGRD,10 m above ground,3 hour fcst,:UGRD:10 m above ground:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,77,51989443,54371057.0,51989443-54371057,2026-04-15,2026-04-15 04:00:00,UGRD,10 m above ground,4 hour fcst,:UGRD:10 m above ground:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,77,52694759,55076373.0,52694759-55076373,2026-04-15,2026-04-15 05:00:00,UGRD,10 m above ground,5 hour fcst,:UGRD:10 m above ground:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,77,53272813,55654427.0,53272813-55654427,2026-04-15,2026-04-15 06:00:00,UGRD,10 m above ground,6 hour fcst,:UGRD:10 m above ground:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,77,54749948,56893419.0,54749948-56893419,2026-04-15,2026-04-15 07:00:00,UGRD,10 m above ground,7 hour fcst,:UGRD:10 m above ground:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,77,54966013,57347627.0,54966013-57347627,2026-04-15,2026-04-15 08:00:00,UGRD,10 m above ground,8 hour fcst,:UGRD:10 m above ground:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,77,55973415,58116886.0,55973415-58116886,2026-04-15,2026-04-15 09:00:00,UGRD,10 m above ground,9 hour fcst,:UGRD:10 m above ground:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,77,56281504,58424975.0,56281504-58424975,2026-04-15,2026-04-15 10:00:00,UGRD,10 m above ground,10 hour fcst,:UGRD:10 m above ground:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,77,56427863,58571334.0,56427863-58571334,2026-04-15,2026-04-15 11:00:00,UGRD,10 m above ground,11 hour fcst,:UGRD:10 m above ground:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,77,56485527,58628998.0,56485527-58628998,2026-04-15,2026-04-15 12:00:00,UGRD,10 m above ground,12 hour fcst,:UGRD:10 m above ground:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,77,56371809,58515280.0,56371809-58515280,2026-04-15,2026-04-15 13:00:00,UGRD,10 m above ground,13 hour fcst,:UGRD:10 m above ground:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,77,56530367,58673838.0,56530367-58673838,2026-04-15,2026-04-15 14:00:00,UGRD,10 m above ground,14 hour fcst,:UGRD:10 m above ground:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,77,56382122,58763736.0,56382122-58763736,2026-04-15,2026-04-15 15:00:00,UGRD,10 m above ground,15 hour fcst,:UGRD:10 m above ground:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,77,55417367,57560838.0,55417367-57560838,2026-04-15,2026-04-15 16:00:00,UGRD,10 m above ground,16 hour fcst,:UGRD:10 m above ground:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,77,54794317,56937788.0,54794317-56937788,2026-04-15,2026-04-15 17:00:00,UGRD,10 m above ground,17 hour fcst,:UGRD:10 m above ground:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,77,54591132,56972746.0,54591132-56972746,2026-04-15,2026-04-15 18:00:00,UGRD,10 m above ground,18 hour fcst,:UGRD:10 m above ground:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,77,54488558,56870172.0,54488558-56870172,2026-04-15,2026-04-15 19:00:00,UGRD,10 m above ground,19 hour fcst,:UGRD:10 m above ground:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,77,53658688,56040302.0,53658688-56040302,2026-04-15,2026-04-15 20:00:00,UGRD,10 m above ground,20 hour fcst,:UGRD:10 m above ground:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,77,53720279,56101893.0,53720279-56101893,2026-04-15,2026-04-15 21:00:00,UGRD,10 m above ground,21 hour fcst,:UGRD:10 m above ground:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,77,54127244,56508858.0,54127244-56508858,2026-04-15,2026-04-15 22:00:00,UGRD,10 m above ground,22 hour fcst,:UGRD:10 m above ground:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,77,54335012,56716626.0,54335012-56716626,2026-04-15,2026-04-15 23:00:00,UGRD,10 m above ground,23 hour fcst,:UGRD:10 m above ground:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,77,54434001,56815615.0,54434001-56815615,2026-04-15,2026-04-16 00:00:00,UGRD,10 m above ground,24 hour fcst,:UGRD:10 m above ground:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,77,54771857,57153471.0,54771857-57153471,2026-04-15,2026-04-16 01:00:00,UGRD,10 m above ground,25 hour fcst,:UGRD:10 m above ground:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,77,54482970,56864584.0,54482970-56864584,2026-04-15,2026-04-16 02:00:00,UGRD,10 m above ground,26 hour fcst,:UGRD:10 m above ground:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,77,55136692,57518306.0,55136692-57518306,2026-04-15,2026-04-16 03:00:00,UGRD,10 m above ground,27 hour fcst,:UGRD:10 m above ground:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,77,56521123,58902737.0,56521123-58902737,2026-04-15,2026-04-16 04:00:00,UGRD,10 m above ground,28 hour fcst,:UGRD:10 m above ground:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,77,56844064,59225678.0,56844064-59225678,2026-04-15,2026-04-16 05:00:00,UGRD,10 m above ground,29 hour fcst,:UGRD:10 m above ground:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,77,56661022,59042636.0,56661022-59042636,2026-04-15,2026-04-16 06:00:00,UGRD,10 m above ground,30 hour fcst,:UGRD:10 m above ground:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,77,57037864,59419478.0,57037864-59419478,2026-04-15,2026-04-16 07:00:00,UGRD,10 m above ground,31 hour fcst,:UGRD:10 m above ground:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,77,57661220,60042834.0,57661220-60042834,2026-04-15,2026-04-16 08:00:00,UGRD,10 m above ground,32 hour fcst,:UGRD:10 m above ground:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,77,57001040,59382654.0,57001040-59382654,2026-04-15,2026-04-16 09:00:00,UGRD,10 m above ground,33 hour fcst,:UGRD:10 m above ground:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,77,57184196,59565810.0,57184196-59565810,2026-04-15,2026-04-16 10:00:00,UGRD,10 m above ground,34 hour fcst,:UGRD:10 m above ground:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,77,56837399,59219013.0,56837399-59219013,2026-04-15,2026-04-16 11:00:00,UGRD,10 m above ground,35 hour fcst,:UGRD:10 m above ground:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,77,56889314,59270928.0,56889314-59270928,2026-04-15,2026-04-16 12:00:00,UGRD,10 m above ground,36 hour fcst,:UGRD:10 m above ground:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,77,57439383,59820997.0,57439383-59820997,2026-04-15,2026-04-16 13:00:00,UGRD,10 m above ground,37 hour fcst,:UGRD:10 m above ground:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,77,57132543,59514157.0,57132543-59514157,2026-04-15,2026-04-16 14:00:00,UGRD,10 m above ground,38 hour fcst,:UGRD:10 m above ground:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,77,56172112,58553726.0,56172112-58553726,2026-04-15,2026-04-16 15:00:00,UGRD,10 m above ground,39 hour fcst,:UGRD:10 m above ground:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,77,55649543,57793014.0,55649543-57793014,2026-04-15,2026-04-16 16:00:00,UGRD,10 m above ground,40 hour fcst,:UGRD:10 m above ground:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,77,55535963,57679434.0,55535963-57679434,2026-04-15,2026-04-16 17:00:00,UGRD,10 m above ground,41 hour fcst,:UGRD:10 m above ground:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,77,54850438,56993909.0,54850438-56993909,2026-04-15,2026-04-16 18:00:00,UGRD,10 m above ground,42 hour fcst,:UGRD:10 m above ground:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,77,54482419,56864033.0,54482419-56864033,2026-04-15,2026-04-16 19:00:00,UGRD,10 m above ground,43 hour fcst,:UGRD:10 m above ground:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,77,54568960,56712431.0,54568960-56712431,2026-04-15,2026-04-16 20:00:00,UGRD,10 m above ground,44 hour fcst,:UGRD:10 m above ground:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,77,54702487,56845958.0,54702487-56845958,2026-04-15,2026-04-16 21:00:00,UGRD,10 m above ground,45 hour fcst,:UGRD:10 m above ground:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,77,54843741,56987212.0,54843741-56987212,2026-04-15,2026-04-16 22:00:00,UGRD,10 m above ground,46 hour fcst,:UGRD:10 m above ground:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,77,54710163,56853634.0,54710163-56853634,2026-04-15,2026-04-16 23:00:00,UGRD,10 m above ground,47 hour fcst,:UGRD:10 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,77,53795434,55938905.0,53795434-55938905,2026-04-15,2026-04-17 00:00:00,UGRD,10 m above ground,48 hour fcst,:UGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [19]:
H.inventory(':VGRD:10 m above')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,78,46846083,48989554.0,46846083-48989554,2026-04-15,2026-04-15 00:00:00,VGRD,10 m above ground,anl,:VGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,78,52774510,55156124.0,52774510-55156124,2026-04-15,2026-04-15 01:00:00,VGRD,10 m above ground,1 hour fcst,:VGRD:10 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,78,53307129,55688743.0,53307129-55688743,2026-04-15,2026-04-15 02:00:00,VGRD,10 m above ground,2 hour fcst,:VGRD:10 m above ground:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,78,54172423,56554037.0,54172423-56554037,2026-04-15,2026-04-15 03:00:00,VGRD,10 m above ground,3 hour fcst,:VGRD:10 m above ground:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,78,54371058,56752672.0,54371058-56752672,2026-04-15,2026-04-15 04:00:00,VGRD,10 m above ground,4 hour fcst,:VGRD:10 m above ground:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,78,55076374,57457988.0,55076374-57457988,2026-04-15,2026-04-15 05:00:00,VGRD,10 m above ground,5 hour fcst,:VGRD:10 m above ground:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,78,55654428,58036042.0,55654428-58036042,2026-04-15,2026-04-15 06:00:00,VGRD,10 m above ground,6 hour fcst,:VGRD:10 m above ground:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,78,56893420,59036891.0,56893420-59036891,2026-04-15,2026-04-15 07:00:00,VGRD,10 m above ground,7 hour fcst,:VGRD:10 m above ground:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,78,57347628,59491099.0,57347628-59491099,2026-04-15,2026-04-15 08:00:00,VGRD,10 m above ground,8 hour fcst,:VGRD:10 m above ground:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,78,58116887,60260358.0,58116887-60260358,2026-04-15,2026-04-15 09:00:00,VGRD,10 m above ground,9 hour fcst,:VGRD:10 m above ground:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,78,58424976,60568447.0,58424976-60568447,2026-04-15,2026-04-15 10:00:00,VGRD,10 m above ground,10 hour fcst,:VGRD:10 m above ground:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,78,58571335,60714806.0,58571335-60714806,2026-04-15,2026-04-15 11:00:00,VGRD,10 m above ground,11 hour fcst,:VGRD:10 m above ground:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,78,58628999,61010613.0,58628999-61010613,2026-04-15,2026-04-15 12:00:00,VGRD,10 m above ground,12 hour fcst,:VGRD:10 m above ground:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,78,58515281,60896895.0,58515281-60896895,2026-04-15,2026-04-15 13:00:00,VGRD,10 m above ground,13 hour fcst,:VGRD:10 m above ground:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,78,58673839,60817310.0,58673839-60817310,2026-04-15,2026-04-15 14:00:00,VGRD,10 m above ground,14 hour fcst,:VGRD:10 m above ground:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,78,58763737,61145351.0,58763737-61145351,2026-04-15,2026-04-15 15:00:00,VGRD,10 m above ground,15 hour fcst,:VGRD:10 m above ground:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,78,57560839,59942453.0,57560839-59942453,2026-04-15,2026-04-15 16:00:00,VGRD,10 m above ground,16 hour fcst,:VGRD:10 m above ground:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,78,56937789,59319403.0,56937789-59319403,2026-04-15,2026-04-15 17:00:00,VGRD,10 m above ground,17 hour fcst,:VGRD:10 m above ground:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,78,56972747,59354361.0,56972747-59354361,2026-04-15,2026-04-15 18:00:00,VGRD,10 m above ground,18 hour fcst,:VGRD:10 m above ground:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,78,56870173,59251787.0,56870173-59251787,2026-04-15,2026-04-15 19:00:00,VGRD,10 m above ground,19 hour fcst,:VGRD:10 m above ground:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,78,56040303,58421917.0,56040303-58421917,2026-04-15,2026-04-15 20:00:00,VGRD,10 m above ground,20 hour fcst,:VGRD:10 m above ground:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,78,56101894,58483508.0,56101894-58483508,2026-04-15,2026-04-15 21:00:00,VGRD,10 m above ground,21 hour fcst,:VGRD:10 m above ground:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,78,56508859,58890473.0,56508859-58890473,2026-04-15,2026-04-15 22:00:00,VGRD,10 m above ground,22 hour fcst,:VGRD:10 m above ground:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,78,56716627,59098241.0,56716627-59098241,2026-04-15,2026-04-15 23:00:00,VGRD,10 m above ground,23 hour fcst,:VGRD:10 m above ground:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,78,56815616,59197230.0,56815616-59197230,2026-04-15,2026-04-16 00:00:00,VGRD,10 m above ground,24 hour fcst,:VGRD:10 m above ground:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,78,57153472,59535086.0,57153472-59535086,2026-04-15,2026-04-16 01:00:00,VGRD,10 m above ground,25 hour fcst,:VGRD:10 m above ground:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,78,56864585,59246199.0,56864585-59246199,2026-04-15,2026-04-16 02:00:00,VGRD,10 m above ground,26 hour fcst,:VGRD:10 m above ground:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,78,57518307,59899921.0,57518307-59899921,2026-04-15,2026-04-16 03:00:00,VGRD,10 m above ground,27 hour fcst,:VGRD:10 m above ground:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,78,58902738,61046209.0,58902738-61046209,2026-04-15,2026-04-16 04:00:00,VGRD,10 m above ground,28 hour fcst,:VGRD:10 m above ground:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,78,59225679,61369150.0,59225679-61369150,2026-04-15,2026-04-16 05:00:00,VGRD,10 m above ground,29 hour fcst,:VGRD:10 m above ground:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,78,59042637,61424251.0,59042637-61424251,2026-04-15,2026-04-16 06:00:00,VGRD,10 m above ground,30 hour fcst,:VGRD:10 m above ground:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,78,59419479,61801093.0,59419479-61801093,2026-04-15,2026-04-16 07:00:00,VGRD,10 m above ground,31 hour fcst,:VGRD:10 m above ground:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,78,60042835,62424449.0,60042835-62424449,2026-04-15,2026-04-16 08:00:00,VGRD,10 m above ground,32 hour fcst,:VGRD:10 m above ground:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,78,59382655,61526126.0,59382655-61526126,2026-04-15,2026-04-16 09:00:00,VGRD,10 m above ground,33 hour fcst,:VGRD:10 m above ground:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,78,59565811,61709282.0,59565811-61709282,2026-04-15,2026-04-16 10:00:00,VGRD,10 m above ground,34 hour fcst,:VGRD:10 m above ground:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,78,59219014,61362485.0,59219014-61362485,2026-04-15,2026-04-16 11:00:00,VGRD,10 m above ground,35 hour fcst,:VGRD:10 m above ground:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,78,59270929,61652543.0,59270929-61652543,2026-04-15,2026-04-16 12:00:00,VGRD,10 m above ground,36 hour fcst,:VGRD:10 m above ground:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,78,59820998,61964469.0,59820998-61964469,2026-04-15,2026-04-16 13:00:00,VGRD,10 m above ground,37 hour fcst,:VGRD:10 m above ground:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,78,59514158,61895772.0,59514158-61895772,2026-04-15,2026-04-16 14:00:00,VGRD,10 m above ground,38 hour fcst,:VGRD:10 m above ground:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,78,58553727,60935341.0,58553727-60935341,2026-04-15,2026-04-16 15:00:00,VGRD,10 m above ground,39 hour fcst,:VGRD:10 m above ground:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,78,57793015,60174629.0,57793015-60174629,2026-04-15,2026-04-16 16:00:00,VGRD,10 m above ground,40 hour fcst,:VGRD:10 m above ground:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,78,57679435,59822906.0,57679435-59822906,2026-04-15,2026-04-16 17:00:00,VGRD,10 m above ground,41 hour fcst,:VGRD:10 m above ground:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,78,56993910,59137381.0,56993910-59137381,2026-04-15,2026-04-16 18:00:00,VGRD,10 m above ground,42 hour fcst,:VGRD:10 m above ground:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,78,56864034,59245648.0,56864034-59245648,2026-04-15,2026-04-16 19:00:00,VGRD,10 m above ground,43 hour fcst,:VGRD:10 m above ground:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,78,56712432,59094046.0,56712432-59094046,2026-04-15,2026-04-16 20:00:00,VGRD,10 m above ground,44 hour fcst,:VGRD:10 m above ground:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,78,56845959,59227573.0,56845959-59227573,2026-04-15,2026-04-16 21:00:00,VGRD,10 m above ground,45 hour fcst,:VGRD:10 m above ground:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,78,56987213,59368827.0,56987213-59368827,2026-04-15,2026-04-16 22:00:00,VGRD,10 m above ground,46 hour fcst,:VGRD:10 m above ground:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,78,56853635,59235249.0,56853635-59235249,2026-04-15,2026-04-16 23:00:00,VGRD,10 m above ground,47 hour fcst,:VGRD:10 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,78,55938906,58320520.0,55938906-58320520,2026-04-15,2026-04-17 00:00:00,VGRD,10 m above ground,48 hour fcst,:VGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [20]:
ss = "(:TMP:2 m|:CAPE:surface:|:TCDC:entire|:CIN:surface:|:UGRD:10 m above|:VGRD:10 m above|:DPT:2 m above)"
H.inventory(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,71,37436570,38658796.0,37436570-38658796,2026-04-15,2026-04-15,TMP,2 m above ground,anl,:TMP:2 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,74,41245489,42471688.0,41245489-42471688,2026-04-15,2026-04-15,DPT,2 m above ground,anl,:DPT:2 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,77,44464468,46846082.0,44464468-46846082,2026-04-15,2026-04-15,UGRD,10 m above ground,anl,:UGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,78,46846083,48989554.0,46846083-48989554,2026-04-15,2026-04-15,VGRD,10 m above ground,anl,:VGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,105,63803507,64409415.0,63803507-64409415,2026-04-15,2026-04-15,CAPE,surface,anl,:CAPE:surface:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
...,...,...,...,...,...,...,...,...,...,...,...
338,77,53795434,55938905.0,53795434-55938905,2026-04-15,2026-04-17,UGRD,10 m above ground,48 hour fcst,:UGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
339,78,55938906,58320520.0,55938906-58320520,2026-04-15,2026-04-17,VGRD,10 m above ground,48 hour fcst,:VGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
340,108,77733767,78286761.0,77733767-78286761,2026-04-15,2026-04-17,CAPE,surface,48 hour fcst,:CAPE:surface:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
341,109,78286762,78999609.0,78286762-78999609,2026-04-15,2026-04-17,CIN,surface,48 hour fcst,:CIN:surface:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
342,119,86780174,87598781.0,86780174-87598781,2026-04-15,2026-04-17,TCDC,entire atmosphere,48 hour fcst,:TCDC:entire atmosphere:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [21]:
fp = H.download(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

In [22]:
fp

[PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d69443a__hrrr.t00z.wrfsfcf17.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8de45294__hrrr.t00z.wrfsfcf01.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8db8443a__hrrr.t00z.wrfsfcf15.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1a443a__hrrr.t00z.wrfsfcf05.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d9e443a__hrrr.t00z.wrfsfcf09.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d4b443a__hrrr.t00z.wrfsfcf04.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8def5294__hrrr.t00z.wrfsfcf00.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dd4443a__hrrr.t00z.wrfsfcf10.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbe443a__hrrr.t00z.wrfsfcf13.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8db2443a__hrrr.t00z.wrfsfcf06.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dc5443a__hrrr.t00z.wrfsfcf08.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbe443a__hrrr.t00z.wrfsfcf16.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d89443a__hrrr.t00z.wrfsfcf18.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d18443a__hrrr.t00z.wrfsfcf14.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8da4443a__hrrr.t00z.wrfsfcf11.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d15443a__hrrr.t00z.wrfsfcf03.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d21443a__hrrr.t00z.wrfsfcf02.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbc443a__hrrr.t00z.wrfsfcf19.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dc7443a__hrrr.t00z.wrfsfcf07.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d12443a__hrrr.t00z.wrfsfcf12.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d86443a__hrrr.t00z.wrfsfcf21.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d20443a__hrrr.t00z.wrfsfcf20.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d11443a__hrrr.t00z.wrfsfcf22.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dd2443a__hrrr.t00z.wrfsfcf28.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1e443a__hrrr.t00z.wrfsfcf27.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8db5443a__hrrr.t00z.wrfsfcf23.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dce443a__hrrr.t00z.wrfsfcf29.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dcc443a__hrrr.t00z.wrfsfcf26.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8df8443a__hrrr.t00z.wrfsfcf31.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d0e443a__hrrr.t00z.wrfsfcf24.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d60443a__hrrr.t00z.wrfsfcf30.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1b443a__hrrr.t00z.wrfsfcf33.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d30443a__hrrr.t00z.wrfsfcf25.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d3a443a__hrrr.t00z.wrfsfcf37.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d0e443a__hrrr.t00z.wrfsfcf36.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d58443a__hrrr.t00z.wrfsfcf32.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbe443a__hrrr.t00z.wrfsfcf34.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d0f443a__hrrr.t00z.wrfsfcf38.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d48443a__hrrr.t00z.wrfsfcf39.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d69443a__hrrr.t00z.wrfsfcf43.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8de7443a__hrrr.t00z.wrfsfcf42.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d61443a__hrrr.t00z.wrfsfcf45.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dde443a__hrrr.t00z.wrfsfcf41.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d64443a__hrrr.t00z.wrfsfcf40.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dac443a__hrrr.t00z.wrfsfcf46.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dc2443a__hrrr.t00z.wrfsfcf44.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1e443a__hrrr.t00z.wrfsfcf35.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1c443a__hrrr.t00z.wrfsfcf48.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8de4443a__hrrr.t00z.wrfsfcf47.grib2')]

In [23]:
ds = xr.open_mfdataset(fp, combine='nested', concat_dim='valid_time')

skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==166 shortName='v10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(2.0)) new_value=Variable(dimensions=(), data=np.float64(10.0))
skipping variable: paramId==165 shortName='u10'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^

In [24]:
ds

<xarray.Dataset> Size: 2GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15T17:00:00 ....
    time               datetime64[ns] 8B 2026-04-15
    step               (valid_time) timedelta64[ns] 392B 17:00:00 ... 1 days ...
    heightAboveGround  float64 8B 2.0
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B 0.0
    atmosphere         float64 8B 0.0
Dimensions without coordinates: y, x
Data variables:
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    d2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    cape               (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    cin                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:19 GRIB to CDM+CF via cfgrib-0.9.1...

In [25]:
ds = ds.sortby('valid_time')
ds

<xarray.Dataset> Size: 2GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15 ... 2026-0...
    time               datetime64[ns] 8B 2026-04-15
    step               (valid_time) timedelta64[ns] 392B 00:00:00 ... 2 days ...
    heightAboveGround  float64 8B 2.0
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B 0.0
    atmosphere         float64 8B 0.0
Dimensions without coordinates: y, x
Data variables:
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    d2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    cape               (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    cin                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:19 GRIB to CDM+CF via cfgrib-0.9.1...

In [26]:
filename = 'nowhrrr.nc'

In [27]:
ds.to_netcdf(filename)