In [3]:
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

# U and V Component download only!

In [1]:
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

In [2]:
run = "2026-04-15 00:00" #must be 00:00 to not drop files.

In [3]:
H = FastHerbie([run], model="hrrr", fxx=np.arange(0,49,1).tolist(), save_dir='meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads', overwrite=True)

In [4]:
H.inventory(':UGRD:10 m above')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,77,44464468,46846082.0,44464468-46846082,2026-04-15,2026-04-15 00:00:00,UGRD,10 m above ground,anl,:UGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,77,50392895,52774509.0,50392895-52774509,2026-04-15,2026-04-15 01:00:00,UGRD,10 m above ground,1 hour fcst,:UGRD:10 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,77,50925514,53307128.0,50925514-53307128,2026-04-15,2026-04-15 02:00:00,UGRD,10 m above ground,2 hour fcst,:UGRD:10 m above ground:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,77,51790808,54172422.0,51790808-54172422,2026-04-15,2026-04-15 03:00:00,UGRD,10 m above ground,3 hour fcst,:UGRD:10 m above ground:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,77,51989443,54371057.0,51989443-54371057,2026-04-15,2026-04-15 04:00:00,UGRD,10 m above ground,4 hour fcst,:UGRD:10 m above ground:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,77,52694759,55076373.0,52694759-55076373,2026-04-15,2026-04-15 05:00:00,UGRD,10 m above ground,5 hour fcst,:UGRD:10 m above ground:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,77,53272813,55654427.0,53272813-55654427,2026-04-15,2026-04-15 06:00:00,UGRD,10 m above ground,6 hour fcst,:UGRD:10 m above ground:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,77,54749948,56893419.0,54749948-56893419,2026-04-15,2026-04-15 07:00:00,UGRD,10 m above ground,7 hour fcst,:UGRD:10 m above ground:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,77,54966013,57347627.0,54966013-57347627,2026-04-15,2026-04-15 08:00:00,UGRD,10 m above ground,8 hour fcst,:UGRD:10 m above ground:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,77,55973415,58116886.0,55973415-58116886,2026-04-15,2026-04-15 09:00:00,UGRD,10 m above ground,9 hour fcst,:UGRD:10 m above ground:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,77,56281504,58424975.0,56281504-58424975,2026-04-15,2026-04-15 10:00:00,UGRD,10 m above ground,10 hour fcst,:UGRD:10 m above ground:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,77,56427863,58571334.0,56427863-58571334,2026-04-15,2026-04-15 11:00:00,UGRD,10 m above ground,11 hour fcst,:UGRD:10 m above ground:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,77,56485527,58628998.0,56485527-58628998,2026-04-15,2026-04-15 12:00:00,UGRD,10 m above ground,12 hour fcst,:UGRD:10 m above ground:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,77,56371809,58515280.0,56371809-58515280,2026-04-15,2026-04-15 13:00:00,UGRD,10 m above ground,13 hour fcst,:UGRD:10 m above ground:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,77,56530367,58673838.0,56530367-58673838,2026-04-15,2026-04-15 14:00:00,UGRD,10 m above ground,14 hour fcst,:UGRD:10 m above ground:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,77,56382122,58763736.0,56382122-58763736,2026-04-15,2026-04-15 15:00:00,UGRD,10 m above ground,15 hour fcst,:UGRD:10 m above ground:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,77,55417367,57560838.0,55417367-57560838,2026-04-15,2026-04-15 16:00:00,UGRD,10 m above ground,16 hour fcst,:UGRD:10 m above ground:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,77,54794317,56937788.0,54794317-56937788,2026-04-15,2026-04-15 17:00:00,UGRD,10 m above ground,17 hour fcst,:UGRD:10 m above ground:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,77,54591132,56972746.0,54591132-56972746,2026-04-15,2026-04-15 18:00:00,UGRD,10 m above ground,18 hour fcst,:UGRD:10 m above ground:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,77,54488558,56870172.0,54488558-56870172,2026-04-15,2026-04-15 19:00:00,UGRD,10 m above ground,19 hour fcst,:UGRD:10 m above ground:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,77,53658688,56040302.0,53658688-56040302,2026-04-15,2026-04-15 20:00:00,UGRD,10 m above ground,20 hour fcst,:UGRD:10 m above ground:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,77,53720279,56101893.0,53720279-56101893,2026-04-15,2026-04-15 21:00:00,UGRD,10 m above ground,21 hour fcst,:UGRD:10 m above ground:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,77,54127244,56508858.0,54127244-56508858,2026-04-15,2026-04-15 22:00:00,UGRD,10 m above ground,22 hour fcst,:UGRD:10 m above ground:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,77,54335012,56716626.0,54335012-56716626,2026-04-15,2026-04-15 23:00:00,UGRD,10 m above ground,23 hour fcst,:UGRD:10 m above ground:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,77,54434001,56815615.0,54434001-56815615,2026-04-15,2026-04-16 00:00:00,UGRD,10 m above ground,24 hour fcst,:UGRD:10 m above ground:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,77,54771857,57153471.0,54771857-57153471,2026-04-15,2026-04-16 01:00:00,UGRD,10 m above ground,25 hour fcst,:UGRD:10 m above ground:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,77,54482970,56864584.0,54482970-56864584,2026-04-15,2026-04-16 02:00:00,UGRD,10 m above ground,26 hour fcst,:UGRD:10 m above ground:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,77,55136692,57518306.0,55136692-57518306,2026-04-15,2026-04-16 03:00:00,UGRD,10 m above ground,27 hour fcst,:UGRD:10 m above ground:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,77,56521123,58902737.0,56521123-58902737,2026-04-15,2026-04-16 04:00:00,UGRD,10 m above ground,28 hour fcst,:UGRD:10 m above ground:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,77,56844064,59225678.0,56844064-59225678,2026-04-15,2026-04-16 05:00:00,UGRD,10 m above ground,29 hour fcst,:UGRD:10 m above ground:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,77,56661022,59042636.0,56661022-59042636,2026-04-15,2026-04-16 06:00:00,UGRD,10 m above ground,30 hour fcst,:UGRD:10 m above ground:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,77,57037864,59419478.0,57037864-59419478,2026-04-15,2026-04-16 07:00:00,UGRD,10 m above ground,31 hour fcst,:UGRD:10 m above ground:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,77,57661220,60042834.0,57661220-60042834,2026-04-15,2026-04-16 08:00:00,UGRD,10 m above ground,32 hour fcst,:UGRD:10 m above ground:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,77,57001040,59382654.0,57001040-59382654,2026-04-15,2026-04-16 09:00:00,UGRD,10 m above ground,33 hour fcst,:UGRD:10 m above ground:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,77,57184196,59565810.0,57184196-59565810,2026-04-15,2026-04-16 10:00:00,UGRD,10 m above ground,34 hour fcst,:UGRD:10 m above ground:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,77,56837399,59219013.0,56837399-59219013,2026-04-15,2026-04-16 11:00:00,UGRD,10 m above ground,35 hour fcst,:UGRD:10 m above ground:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,77,56889314,59270928.0,56889314-59270928,2026-04-15,2026-04-16 12:00:00,UGRD,10 m above ground,36 hour fcst,:UGRD:10 m above ground:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,77,57439383,59820997.0,57439383-59820997,2026-04-15,2026-04-16 13:00:00,UGRD,10 m above ground,37 hour fcst,:UGRD:10 m above ground:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,77,57132543,59514157.0,57132543-59514157,2026-04-15,2026-04-16 14:00:00,UGRD,10 m above ground,38 hour fcst,:UGRD:10 m above ground:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,77,56172112,58553726.0,56172112-58553726,2026-04-15,2026-04-16 15:00:00,UGRD,10 m above ground,39 hour fcst,:UGRD:10 m above ground:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,77,55649543,57793014.0,55649543-57793014,2026-04-15,2026-04-16 16:00:00,UGRD,10 m above ground,40 hour fcst,:UGRD:10 m above ground:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,77,55535963,57679434.0,55535963-57679434,2026-04-15,2026-04-16 17:00:00,UGRD,10 m above ground,41 hour fcst,:UGRD:10 m above ground:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,77,54850438,56993909.0,54850438-56993909,2026-04-15,2026-04-16 18:00:00,UGRD,10 m above ground,42 hour fcst,:UGRD:10 m above ground:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,77,54482419,56864033.0,54482419-56864033,2026-04-15,2026-04-16 19:00:00,UGRD,10 m above ground,43 hour fcst,:UGRD:10 m above ground:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,77,54568960,56712431.0,54568960-56712431,2026-04-15,2026-04-16 20:00:00,UGRD,10 m above ground,44 hour fcst,:UGRD:10 m above ground:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,77,54702487,56845958.0,54702487-56845958,2026-04-15,2026-04-16 21:00:00,UGRD,10 m above ground,45 hour fcst,:UGRD:10 m above ground:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,77,54843741,56987212.0,54843741-56987212,2026-04-15,2026-04-16 22:00:00,UGRD,10 m above ground,46 hour fcst,:UGRD:10 m above ground:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,77,54710163,56853634.0,54710163-56853634,2026-04-15,2026-04-16 23:00:00,UGRD,10 m above ground,47 hour fcst,:UGRD:10 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,77,53795434,55938905.0,53795434-55938905,2026-04-15,2026-04-17 00:00:00,UGRD,10 m above ground,48 hour fcst,:UGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [5]:
H.inventory(':VGRD:10 m above')

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,78,46846083,48989554.0,46846083-48989554,2026-04-15,2026-04-15 00:00:00,VGRD,10 m above ground,anl,:VGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,78,52774510,55156124.0,52774510-55156124,2026-04-15,2026-04-15 01:00:00,VGRD,10 m above ground,1 hour fcst,:VGRD:10 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,78,53307129,55688743.0,53307129-55688743,2026-04-15,2026-04-15 02:00:00,VGRD,10 m above ground,2 hour fcst,:VGRD:10 m above ground:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,78,54172423,56554037.0,54172423-56554037,2026-04-15,2026-04-15 03:00:00,VGRD,10 m above ground,3 hour fcst,:VGRD:10 m above ground:3 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,78,54371058,56752672.0,54371058-56752672,2026-04-15,2026-04-15 04:00:00,VGRD,10 m above ground,4 hour fcst,:VGRD:10 m above ground:4 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
5,78,55076374,57457988.0,55076374-57457988,2026-04-15,2026-04-15 05:00:00,VGRD,10 m above ground,5 hour fcst,:VGRD:10 m above ground:5 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
6,78,55654428,58036042.0,55654428-58036042,2026-04-15,2026-04-15 06:00:00,VGRD,10 m above ground,6 hour fcst,:VGRD:10 m above ground:6 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
7,78,56893420,59036891.0,56893420-59036891,2026-04-15,2026-04-15 07:00:00,VGRD,10 m above ground,7 hour fcst,:VGRD:10 m above ground:7 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
8,78,57347628,59491099.0,57347628-59491099,2026-04-15,2026-04-15 08:00:00,VGRD,10 m above ground,8 hour fcst,:VGRD:10 m above ground:8 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
9,78,58116887,60260358.0,58116887-60260358,2026-04-15,2026-04-15 09:00:00,VGRD,10 m above ground,9 hour fcst,:VGRD:10 m above ground:9 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
10,78,58424976,60568447.0,58424976-60568447,2026-04-15,2026-04-15 10:00:00,VGRD,10 m above ground,10 hour fcst,:VGRD:10 m above ground:10 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
11,78,58571335,60714806.0,58571335-60714806,2026-04-15,2026-04-15 11:00:00,VGRD,10 m above ground,11 hour fcst,:VGRD:10 m above ground:11 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
12,78,58628999,61010613.0,58628999-61010613,2026-04-15,2026-04-15 12:00:00,VGRD,10 m above ground,12 hour fcst,:VGRD:10 m above ground:12 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
13,78,58515281,60896895.0,58515281-60896895,2026-04-15,2026-04-15 13:00:00,VGRD,10 m above ground,13 hour fcst,:VGRD:10 m above ground:13 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
14,78,58673839,60817310.0,58673839-60817310,2026-04-15,2026-04-15 14:00:00,VGRD,10 m above ground,14 hour fcst,:VGRD:10 m above ground:14 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
15,78,58763737,61145351.0,58763737-61145351,2026-04-15,2026-04-15 15:00:00,VGRD,10 m above ground,15 hour fcst,:VGRD:10 m above ground:15 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
16,78,57560839,59942453.0,57560839-59942453,2026-04-15,2026-04-15 16:00:00,VGRD,10 m above ground,16 hour fcst,:VGRD:10 m above ground:16 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
17,78,56937789,59319403.0,56937789-59319403,2026-04-15,2026-04-15 17:00:00,VGRD,10 m above ground,17 hour fcst,:VGRD:10 m above ground:17 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
18,78,56972747,59354361.0,56972747-59354361,2026-04-15,2026-04-15 18:00:00,VGRD,10 m above ground,18 hour fcst,:VGRD:10 m above ground:18 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
19,78,56870173,59251787.0,56870173-59251787,2026-04-15,2026-04-15 19:00:00,VGRD,10 m above ground,19 hour fcst,:VGRD:10 m above ground:19 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
20,78,56040303,58421917.0,56040303-58421917,2026-04-15,2026-04-15 20:00:00,VGRD,10 m above ground,20 hour fcst,:VGRD:10 m above ground:20 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
21,78,56101894,58483508.0,56101894-58483508,2026-04-15,2026-04-15 21:00:00,VGRD,10 m above ground,21 hour fcst,:VGRD:10 m above ground:21 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
22,78,56508859,58890473.0,56508859-58890473,2026-04-15,2026-04-15 22:00:00,VGRD,10 m above ground,22 hour fcst,:VGRD:10 m above ground:22 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
23,78,56716627,59098241.0,56716627-59098241,2026-04-15,2026-04-15 23:00:00,VGRD,10 m above ground,23 hour fcst,:VGRD:10 m above ground:23 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
24,78,56815616,59197230.0,56815616-59197230,2026-04-15,2026-04-16 00:00:00,VGRD,10 m above ground,24 hour fcst,:VGRD:10 m above ground:24 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
25,78,57153472,59535086.0,57153472-59535086,2026-04-15,2026-04-16 01:00:00,VGRD,10 m above ground,25 hour fcst,:VGRD:10 m above ground:25 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
26,78,56864585,59246199.0,56864585-59246199,2026-04-15,2026-04-16 02:00:00,VGRD,10 m above ground,26 hour fcst,:VGRD:10 m above ground:26 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
27,78,57518307,59899921.0,57518307-59899921,2026-04-15,2026-04-16 03:00:00,VGRD,10 m above ground,27 hour fcst,:VGRD:10 m above ground:27 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
28,78,58902738,61046209.0,58902738-61046209,2026-04-15,2026-04-16 04:00:00,VGRD,10 m above ground,28 hour fcst,:VGRD:10 m above ground:28 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
29,78,59225679,61369150.0,59225679-61369150,2026-04-15,2026-04-16 05:00:00,VGRD,10 m above ground,29 hour fcst,:VGRD:10 m above ground:29 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
30,78,59042637,61424251.0,59042637-61424251,2026-04-15,2026-04-16 06:00:00,VGRD,10 m above ground,30 hour fcst,:VGRD:10 m above ground:30 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
31,78,59419479,61801093.0,59419479-61801093,2026-04-15,2026-04-16 07:00:00,VGRD,10 m above ground,31 hour fcst,:VGRD:10 m above ground:31 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
32,78,60042835,62424449.0,60042835-62424449,2026-04-15,2026-04-16 08:00:00,VGRD,10 m above ground,32 hour fcst,:VGRD:10 m above ground:32 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
33,78,59382655,61526126.0,59382655-61526126,2026-04-15,2026-04-16 09:00:00,VGRD,10 m above ground,33 hour fcst,:VGRD:10 m above ground:33 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
34,78,59565811,61709282.0,59565811-61709282,2026-04-15,2026-04-16 10:00:00,VGRD,10 m above ground,34 hour fcst,:VGRD:10 m above ground:34 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
35,78,59219014,61362485.0,59219014-61362485,2026-04-15,2026-04-16 11:00:00,VGRD,10 m above ground,35 hour fcst,:VGRD:10 m above ground:35 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
36,78,59270929,61652543.0,59270929-61652543,2026-04-15,2026-04-16 12:00:00,VGRD,10 m above ground,36 hour fcst,:VGRD:10 m above ground:36 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
37,78,59820998,61964469.0,59820998-61964469,2026-04-15,2026-04-16 13:00:00,VGRD,10 m above ground,37 hour fcst,:VGRD:10 m above ground:37 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
38,78,59514158,61895772.0,59514158-61895772,2026-04-15,2026-04-16 14:00:00,VGRD,10 m above ground,38 hour fcst,:VGRD:10 m above ground:38 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
39,78,58553727,60935341.0,58553727-60935341,2026-04-15,2026-04-16 15:00:00,VGRD,10 m above ground,39 hour fcst,:VGRD:10 m above ground:39 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
40,78,57793015,60174629.0,57793015-60174629,2026-04-15,2026-04-16 16:00:00,VGRD,10 m above ground,40 hour fcst,:VGRD:10 m above ground:40 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
41,78,57679435,59822906.0,57679435-59822906,2026-04-15,2026-04-16 17:00:00,VGRD,10 m above ground,41 hour fcst,:VGRD:10 m above ground:41 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
42,78,56993910,59137381.0,56993910-59137381,2026-04-15,2026-04-16 18:00:00,VGRD,10 m above ground,42 hour fcst,:VGRD:10 m above ground:42 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
43,78,56864034,59245648.0,56864034-59245648,2026-04-15,2026-04-16 19:00:00,VGRD,10 m above ground,43 hour fcst,:VGRD:10 m above ground:43 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
44,78,56712432,59094046.0,56712432-59094046,2026-04-15,2026-04-16 20:00:00,VGRD,10 m above ground,44 hour fcst,:VGRD:10 m above ground:44 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
45,78,56845959,59227573.0,56845959-59227573,2026-04-15,2026-04-16 21:00:00,VGRD,10 m above ground,45 hour fcst,:VGRD:10 m above ground:45 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
46,78,56987213,59368827.0,56987213-59368827,2026-04-15,2026-04-16 22:00:00,VGRD,10 m above ground,46 hour fcst,:VGRD:10 m above ground:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
47,78,56853635,59235249.0,56853635-59235249,2026-04-15,2026-04-16 23:00:00,VGRD,10 m above ground,47 hour fcst,:VGRD:10 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
48,78,55938906,58320520.0,55938906-58320520,2026-04-15,2026-04-17 00:00:00,VGRD,10 m above ground,48 hour fcst,:VGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [7]:
ss = "(:UGRD:10 m above|:VGRD:10 m above)"
H.inventory(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,variable,level,forecast_time,search_this,FILE
0,77,44464468,46846082.0,44464468-46846082,2026-04-15,2026-04-15 00:00:00,UGRD,10 m above ground,anl,:UGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
1,78,46846083,48989554.0,46846083-48989554,2026-04-15,2026-04-15 00:00:00,VGRD,10 m above ground,anl,:VGRD:10 m above ground:anl,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
2,77,50392895,52774509.0,50392895-52774509,2026-04-15,2026-04-15 01:00:00,UGRD,10 m above ground,1 hour fcst,:UGRD:10 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
3,78,52774510,55156124.0,52774510-55156124,2026-04-15,2026-04-15 01:00:00,VGRD,10 m above ground,1 hour fcst,:VGRD:10 m above ground:1 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
4,77,50925514,53307128.0,50925514-53307128,2026-04-15,2026-04-15 02:00:00,UGRD,10 m above ground,2 hour fcst,:UGRD:10 m above ground:2 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
...,...,...,...,...,...,...,...,...,...,...,...
93,78,56987213,59368827.0,56987213-59368827,2026-04-15,2026-04-16 22:00:00,VGRD,10 m above ground,46 hour fcst,:VGRD:10 m above ground:46 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
94,77,54710163,56853634.0,54710163-56853634,2026-04-15,2026-04-16 23:00:00,UGRD,10 m above ground,47 hour fcst,:UGRD:10 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
95,78,56853635,59235249.0,56853635-59235249,2026-04-15,2026-04-16 23:00:00,VGRD,10 m above ground,47 hour fcst,:VGRD:10 m above ground:47 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
96,77,53795434,55938905.0,53795434-55938905,2026-04-15,2026-04-17 00:00:00,UGRD,10 m above ground,48 hour fcst,:UGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...
97,78,55938906,58320520.0,55938906-58320520,2026-04-15,2026-04-17 00:00:00,VGRD,10 m above ground,48 hour fcst,:VGRD:10 m above ground:48 hour fcst,https://noaa-hrrr-bdp-pds.s3.amazonaws.com/hrr...

In [8]:
fp = H.download(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

In [9]:
fp

[PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8de4391b__hrrr.t00z.wrfsfcf01.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d21391b__hrrr.t00z.wrfsfcf02.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d15391b__hrrr.t00z.wrfsfcf03.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbe391b__hrrr.t00z.wrfsfcf13.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8db8391b__hrrr.t00z.wrfsfcf15.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d69391b__hrrr.t00z.wrfsfcf17.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dd4391b__hrrr.t00z.wrfsfcf10.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8da4391b__hrrr.t00z.wrfsfcf11.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1a391b__hrrr.t00z.wrfsfcf05.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dc5391b__hrrr.t00z.wrfsfcf08.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d4b391b__hrrr.t00z.wrfsfcf04.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbe391b__hrrr.t00z.wrfsfcf16.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d18391b__hrrr.t00z.wrfsfcf14.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d9e391b__hrrr.t00z.wrfsfcf09.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8db2391b__hrrr.t00z.wrfsfcf06.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8def391b__hrrr.t00z.wrfsfcf00.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d12391b__hrrr.t00z.wrfsfcf12.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d89391b__hrrr.t00z.wrfsfcf18.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dc7391b__hrrr.t00z.wrfsfcf07.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbc391b__hrrr.t00z.wrfsfcf19.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d20391b__hrrr.t00z.wrfsfcf20.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d86391b__hrrr.t00z.wrfsfcf21.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1e391b__hrrr.t00z.wrfsfcf27.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dcc391b__hrrr.t00z.wrfsfcf26.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d30391b__hrrr.t00z.wrfsfcf25.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dd2391b__hrrr.t00z.wrfsfcf28.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8df8391b__hrrr.t00z.wrfsfcf31.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8db5391b__hrrr.t00z.wrfsfcf23.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d11391b__hrrr.t00z.wrfsfcf22.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d60391b__hrrr.t00z.wrfsfcf30.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d58391b__hrrr.t00z.wrfsfcf32.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d0e391b__hrrr.t00z.wrfsfcf24.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d0e391b__hrrr.t00z.wrfsfcf36.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d0f391b__hrrr.t00z.wrfsfcf38.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dbe391b__hrrr.t00z.wrfsfcf34.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1e391b__hrrr.t00z.wrfsfcf35.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1b391b__hrrr.t00z.wrfsfcf33.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d64391b__hrrr.t00z.wrfsfcf40.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d3a391b__hrrr.t00z.wrfsfcf37.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dde391b__hrrr.t00z.wrfsfcf41.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d69391b__hrrr.t00z.wrfsfcf43.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8de7391b__hrrr.t00z.wrfsfcf42.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d48391b__hrrr.t00z.wrfsfcf39.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dac391b__hrrr.t00z.wrfsfcf46.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8de4391b__hrrr.t00z.wrfsfcf47.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dc2391b__hrrr.t00z.wrfsfcf44.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d61391b__hrrr.t00z.wrfsfcf45.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8d1c391b__hrrr.t00z.wrfsfcf48.grib2'),
 PosixPath('meteo473/sp26_groupwork/473_sp26_group4/NewVariableDownloads/hrrr/20260415/subset_8dce391b__hrrr.t00z.wrfsfcf29.grib2')]

In [10]:
ds = xr.open_mfdataset(fp, combine='nested', concat_dim='valid_time')

/tmp/ipykernel_620067/3885475503.py:1: FutureWarning: In a future version of xarray the default value for coords will change from coords='different' to coords='minimal'. This is likely to lead to different results when multiple datasets have matching variables with overlapping values. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set coords explicitly.
  ds = xr.open_mfdataset(fp, combine='nested', concat_dim='valid_time')

In [11]:
ds

<xarray.Dataset> Size: 777MB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15T01:00:00 ....
    time               datetime64[ns] 8B 2026-04-15
    step               (valid_time) timedelta64[ns] 392B 01:00:00 ... 1 days ...
    heightAboveGround  float64 8B 10.0
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
Dimensions without coordinates: y, x
Data variables:
    u10                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    v10                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:21 GRIB to CDM+CF via cfgrib-0.9.1...

In [12]:
ds = ds.sortby('valid_time')
ds

<xarray.Dataset> Size: 777MB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15 ... 2026-0...
    time               datetime64[ns] 8B 2026-04-15
    step               (valid_time) timedelta64[ns] 392B 00:00:00 ... 2 days ...
    heightAboveGround  float64 8B 10.0
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
Dimensions without coordinates: y, x
Data variables:
    u10                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
    v10                (valid_time, y, x) float32 373MB dask.array<chunksize=(1, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:21 GRIB to CDM+CF via cfgrib-0.9.1...

In [13]:
filename = 'u_and_v_nowhrrr.nc'

In [14]:
ds.to_netcdf(filename)

# Merge Work, do not run

In [15]:
hrrr_u_v = 'u_and_v_nowhrrr.nc'
hrrr = 'nowhrrr.nc'

null_u_v = 'u_and_v_null.nc'
null = 'null2hrrr.nc'

In [16]:
ds1 = xr.open_mfdataset(hrrr_u_v)

sh: 1: getfattr: not found

In [17]:
ds2 = xr.open_mfdataset(hrrr)

sh: 1: getfattr: not found

In [59]:
ds3 = xr.open_mfdataset(null_u_v)

sh: 1: getfattr: not found

In [60]:
ds4 = xr.open_mfdataset(null)

sh: 1: getfattr: not found

In [18]:
ds1

<xarray.Dataset> Size: 777MB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15 ... 2026-0...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B dask.array<chunksize=(49,), meta=np.ndarray>
    heightAboveGround  float64 8B ...
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
Dimensions without coordinates: y, x
Data variables:
    u10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    v10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:21 GRIB to CDM+CF via cfgrib-0.9.1...

In [19]:
ds2

<xarray.Dataset> Size: 2GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15 ... 2026-0...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B dask.array<chunksize=(49,), meta=np.ndarray>
    heightAboveGround  float64 8B ...
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B ...
    atmosphere         float64 8B ...
Dimensions without coordinates: y, x
Data variables:
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    d2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cape               (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cin                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:19 GRIB to CDM+CF via cfgrib-0.9.1...

In [20]:
ds_merge_incident = xr.merge([ds1,ds2], compat = 'override')

In [21]:
ds_merge_incident

<xarray.Dataset> Size: 3GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2026-04-15 ... 2026-0...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B dask.array<chunksize=(49,), meta=np.ndarray>
    heightAboveGround  float64 8B ...
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B ...
    atmosphere         float64 8B ...
Dimensions without coordinates: y, x
Data variables:
    u10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    v10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    d2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cape               (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cin                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-16T18:21 GRIB to CDM+CF via cfgrib-0.9.1...

In [63]:
ds_merge_null = xr.merge([ds3,ds4], compat = 'override')

In [64]:
ds_merge_null

<xarray.Dataset> Size: 3GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2021-10-13 ... 2021-1...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B dask.array<chunksize=(49,), meta=np.ndarray>
    heightAboveGround  float64 8B ...
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B ...
    atmosphere         float64 8B ...
Dimensions without coordinates: y, x
Data variables:
    u10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    v10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    d2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cape               (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cin                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-08T19:04 GRIB to CDM+CF via cfgrib-0.9.1...

In [22]:
filename1 = ('HRRR')
filename2 = ('MergedNull')

In [66]:
ds_merge_null.to_netcdf(filename2)

In [23]:
ds_merge_incident.to_netcdf(filename1)

# Trial

In [69]:
ds_merge_incident

<xarray.Dataset> Size: 3GB
Dimensions:            (valid_time: 49, y: 1059, x: 1799)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2021-10-10 ... 2021-1...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B dask.array<chunksize=(49,), meta=np.ndarray>
    heightAboveGround  float64 8B ...
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B ...
    atmosphere         float64 8B ...
Dimensions without coordinates: y, x
Data variables:
    u10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    v10                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    t2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    d2m                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cape               (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    cin                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
    tcc                (valid_time, y, x) float32 373MB dask.array<chunksize=(49, 1059, 1799), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP
    history:                 2026-04-01T15:45 GRIB to CDM+CF via cfgrib-0.9.1...

In [70]:
u = ds_merge_incident['u10']
v = ds_merge_incident['v10']

In [71]:
convergence = -(u.differentiate('x') + v.differentiate('y'))

In [72]:
convergence

<xarray.DataArray (valid_time: 49, y: 1059, x: 1799)> Size: 373MB
dask.array<neg, shape=(49, 1059, 1799), dtype=float32, chunksize=(49, 1059, 1799), chunktype=numpy.ndarray>
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 392B 2021-10-10 ... 2021-1...
    time               datetime64[ns] 8B ...
    step               (valid_time) timedelta64[ns] 392B dask.array<chunksize=(49,), meta=np.ndarray>
    heightAboveGround  float64 8B ...
    latitude           (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    longitude          (y, x) float64 15MB dask.array<chunksize=(1059, 1799), meta=np.ndarray>
    surface            float64 8B ...
    atmosphere         float64 8B ...
Dimensions without coordinates: y, x